### ISSUE TITLE
The CI doesn't trigger the Clippy action

### ISSUE THREAD

**Issue by dyxushuai** [risc0/zeth#67]
Independent issue for tracking the CI problem. The original discussion: https://github.com/risc0/zeth/pull/64#pullrequestreview-1775562186

My opinion: https://github.com/risc0/zeth/pull/64#issuecomment-1851969881

I think it doesn't add Clippy component in the `risc0/risc0/.github/actions/rustup` action.
Perhaps we can add the snippet:
```
with:
	components: clippy
```

```yaml
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: risc0/risc0/.github/actions/rustup@release-0.18
      with:
        components: clippy
    - uses: risc0/risc0/.github/actions/sccache@release-0.18
    - uses: risc0/clippy-action@main
      with:
        reporter: 'github-pr-check'
        fail_on_error: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clippy_flags: --workspace --all-targets --all-features -- -Dwarnings
```
